added new binary pcrlist

diff --git a/initfs-tpm2/debian/initramfs-tools/hooks/mortar b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
--- a/initfs-tpm2/debian/initramfs-tools/hooks/mortar
+++ b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
@@ -68,9 +68,11 @@ if [ -x /usr/bin/clevis-decrypt-tpm2 ]; then
     tpm2_creatprimary_bin=$(find_binary "tpm2_createprimary")
     tpm2_unseal_bin=$(find_binary "tpm2_unseal")
     tpm2_load_bin=$(find_binary "tpm2_load")
+    tpm2_pcrlist_bin=$(find_binary "tpm2_pcrlist")
     copy_exec "${tpm2_creatprimary_bin}" /bin || die 1 "Unable to copy ${tpm2_creatprimary_bin}" 
     copy_exec "${tpm2_unseal_bin}" /bin || die 1 "Unable to copy ${tpm2_unseal_bin}"
     copy_exec "${tpm2_load_bin}" /bin || die 1 "Unable to copy ${tpm2_load_bin}"
+    copy_exec "${tpm2_pcrlist_bin}" /bin || die 1 "Unable to copy ${tpm2_pcrlist_bin}"
     for _LIBRARY in /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so*; do
         if [ -e "${_LIBRARY}" ]; then
             copy_exec "${_LIBRARY}" || die 2 "Unable to copy ${_LIBRARY}"
