luks tpm2 fixed for debian (I think)

diff --git a/initfs-tpm2/debian/initramfs-tools/hooks/mortar b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
--- a/initfs-tpm2/debian/initramfs-tools/hooks/mortar
+++ b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
@@ -35,7 +35,7 @@ prereqs)
      ;;
 esac
 
-. @initramfstoolsdir@/hook-functions
+. /usr/share/initramfs-tools/hook-functions
 
 die() {
     code="$1"
@@ -60,18 +60,18 @@ if [ -n "${FORCE_CLEVIS}" ] && [ "${FORCE_CLEVIS}" != "n" ]; then
 fi    
 
 
-copy_exec @bindir@/clevis-decrypt-tang || die 1 "@bindir@/clevis-decrypt-tang not found"
-copy_exec @bindir@/clevis-decrypt-sss || die 1 "@bindir@/clevis-decrypt-sss not found"
-copy_exec @bindir@/clevis-decrypt || die 1 "@bindir@/clevis-decrypt not found"
-if [ -x @bindir@/clevis-decrypt-tpm2 ]; then
-    copy_exec @bindir@/clevis-decrypt-tpm2 || die 1 "@bindir@/clevis-decrypt-tpm2 not found"
+copy_exec /usr/bin/clevis-decrypt-tang || die 1 "/usr/bin/clevis-decrypt-tang not found"
+copy_exec /usr/bin/clevis-decrypt-sss || die 1 "/usr/bin/clevis-decrypt-sss not found"
+copy_exec /usr/bin/clevis-decrypt || die 1 "/usr/bin/clevis-decrypt not found"
+if [ -x /usr/bin/clevis-decrypt-tpm2 ]; then
+    copy_exec /usr/bin/clevis-decrypt-tpm2 || die 1 "/usr/bin/clevis-decrypt-tpm2 not found"
     tpm2_creatprimary_bin=$(find_binary "tpm2_createprimary")
     tpm2_unseal_bin=$(find_binary "tpm2_unseal")
     tpm2_load_bin=$(find_binary "tpm2_load")
     copy_exec "${tpm2_creatprimary_bin}" || die 1 "Unable to copy ${tpm2_creatprimary_bin}" 
     copy_exec "${tpm2_unseal_bin}" || die 1 "Unable to copy ${tpm2_unseal_bin}"
     copy_exec "${tpm2_load_bin}" || die 1 "Unable to copy ${tpm2_load_bin}"
-    for _LIBRARY in @libdir@/libtss2-tcti-device.so*; do
+    for _LIBRARY in /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so*; do
         if [ -e "${_LIBRARY}" ]; then
             copy_exec "${_LIBRARY}" || die 2 "Unable to copy ${_LIBRARY}"
         fi
@@ -85,4 +85,4 @@ copy_exec "${luksmeta_bin}" || die 2 "Unable to copy ${luksmeta_bin}"
 copy_exec "${jose_bin}" || die 2 "Unable to copy ${jose_bin}"
 
 
-copy_exec @bindir@/clevis || die 1 "@bindir@/clevis not found"
+copy_exec /usr/bin/clevis || die 1 "/usr/bin/clevis not found"
diff --git a/initfs-tpm2/debian/initramfs-tools/scripts/local-top/mortar b/initfs-tpm2/debian/initramfs-tools/scripts/local-top/mortar
--- a/initfs-tpm2/debian/initramfs-tools/scripts/local-top/mortar
+++ b/initfs-tpm2/debian/initramfs-tools/scripts/local-top/mortar
@@ -4,8 +4,6 @@
 # elements of this script inspired by https://github.com/latchset/clevis/blob/master/src/initramfs-tools/scripts/local-top/clevis.in as it existed on 1/14/2020
 
 
-. /scripts/functions
-
 # THIS BLOCK IS DISABLED FOR NOW. See if we need it...
 # This is a copy  of 'all_netbootable_devices/all_non_enslaved_devices' for
 # platforms that might not provide it.
@@ -71,12 +69,15 @@ HEADERSHA256=
 HEADERFILE=
 TOKENID=
 
+# Test if the disk is already unlocked.
+if [ -e /dev/mapper/"$CRYPTNAME" ]; then exit; fi
+if ! [ -e "$CRYPTDEV" ]; then echo "Cannot find the crypto block device at $CRYPTDEV"; exit 1; fi
 sleep 2
 
 # Verify the LUKS header.
 if [ -f "$HEADERFILE" ]; then rm "$HEADERFILE"; fi
 if cryptsetup luksHeaderBackup "$CRYPTDEV" --header-backup-file "$HEADERFILE"; then
-    HEADERSHA256CUR=$(sha256sum "$HEADERFILE" | cut -f1 -d' ')
+    HEADERSHA256CUR=`sha256sum "$HEADERFILE" | cut -f1 -d' '`
     if [ "$HEADERSHA256" == "$HEADERSHA256CUR" ]; then
         echo "HEADER VALIDATION SUCCEEDED."
     else
@@ -108,7 +109,7 @@ fi
 # If LUKS2
 if cryptsetup isLuks --type luks2 "$CRYPTDEV"; then
 	# jose jwe fmt -c outputs extra \n, so clean it up and pass to disk for unlocking.
-	key=`cryptsetup token export --token-id "$TOKENID" | jose fmt -j- -Og jwe -o- | jose jwe fmt -i- -c | tr -d '\n'`
+	key=`cryptsetup token export --token-id "$TOKENID" "$CRYPTDEV" | jose fmt -j- -Og jwe -o- | jose jwe fmt -i- -c | tr -d '\n'`
 	if echo -n "$key" | clevis decrypt | cryptsetup luksOpen "$CRYPTDEV" "$CRYPTNAME"; then
 		RESULT="pass"
 	else
