missed a couple dest paths

diff --git a/initfs-tpm2/debian/initramfs-tools/hooks/mortar b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
--- a/initfs-tpm2/debian/initramfs-tools/hooks/mortar
+++ b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
@@ -68,9 +68,9 @@ if [ -x /usr/bin/clevis-decrypt-tpm2 ]; then
     tpm2_creatprimary_bin=$(find_binary "tpm2_createprimary")
     tpm2_unseal_bin=$(find_binary "tpm2_unseal")
     tpm2_load_bin=$(find_binary "tpm2_load")
-    copy_exec "${tpm2_creatprimary_bin}" || die 1 "Unable to copy ${tpm2_creatprimary_bin}" 
-    copy_exec "${tpm2_unseal_bin}" || die 1 "Unable to copy ${tpm2_unseal_bin}"
-    copy_exec "${tpm2_load_bin}" || die 1 "Unable to copy ${tpm2_load_bin}"
+    copy_exec "${tpm2_creatprimary_bin}" /bin || die 1 "Unable to copy ${tpm2_creatprimary_bin}" 
+    copy_exec "${tpm2_unseal_bin}" /bin || die 1 "Unable to copy ${tpm2_unseal_bin}"
+    copy_exec "${tpm2_load_bin}" /bin || die 1 "Unable to copy ${tpm2_load_bin}"
     for _LIBRARY in /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so*; do
         if [ -e "${_LIBRARY}" ]; then
             copy_exec "${_LIBRARY}" || die 2 "Unable to copy ${_LIBRARY}"
@@ -84,4 +84,4 @@ jose_bin=$(find_binary "jose")
 bash_bin=$(find_binary "bash")
 copy_exec "${luksmeta_bin}" /bin || die 2 "Unable to copy ${luksmeta_bin}"
 copy_exec "${jose_bin}" /bin || die 2 "Unable to copy ${jose_bin}"
-copy_exec "${bash_bin}" || die 2 "Unable to copy ${bash_bin} to initrd image"
+copy_exec "${bash_bin}" /bin || die 2 "Unable to copy ${bash_bin} to initrd image"
