fixed pathing issues

diff --git a/initfs-tpm2/debian/initramfs-tools/hooks/mortar b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
--- a/initfs-tpm2/debian/initramfs-tools/hooks/mortar
+++ b/initfs-tpm2/debian/initramfs-tools/hooks/mortar
@@ -59,12 +59,12 @@ if [ -n "${FORCE_CLEVIS}" ] && [ "${FORCE_CLEVIS}" != "n" ]; then
     done
 fi    
 
-
-copy_exec /usr/bin/clevis-decrypt-tang || die 1 "/usr/bin/clevis-decrypt-tang not found"
-copy_exec /usr/bin/clevis-decrypt-sss || die 1 "/usr/bin/clevis-decrypt-sss not found"
-copy_exec /usr/bin/clevis-decrypt || die 1 "/usr/bin/clevis-decrypt not found"
+copy_exec /usr/bin/clevis /bin || die 1 "/usr/bin/clevis not found"
+copy_exec /usr/bin/clevis-decrypt-tang /bin || die 1 "/usr/bin/clevis-decrypt-tang not found"
+copy_exec /usr/bin/clevis-decrypt-sss /bin || die 1 "/usr/bin/clevis-decrypt-sss not found"
+copy_exec /usr/bin/clevis-decrypt /bin || die 1 "/usr/bin/clevis-decrypt not found"
 if [ -x /usr/bin/clevis-decrypt-tpm2 ]; then
-    copy_exec /usr/bin/clevis-decrypt-tpm2 || die 1 "/usr/bin/clevis-decrypt-tpm2 not found"
+    copy_exec /usr/bin/clevis-decrypt-tpm2 /bin || die 1 "/usr/bin/clevis-decrypt-tpm2 not found"
     tpm2_creatprimary_bin=$(find_binary "tpm2_createprimary")
     tpm2_unseal_bin=$(find_binary "tpm2_unseal")
     tpm2_load_bin=$(find_binary "tpm2_load")
@@ -81,8 +81,6 @@ fi
 
 luksmeta_bin=$(find_binary "luksmeta")
 jose_bin=$(find_binary "jose")
-copy_exec "${luksmeta_bin}" || die 2 "Unable to copy ${luksmeta_bin}"
-copy_exec "${jose_bin}" || die 2 "Unable to copy ${jose_bin}"
+copy_exec "${luksmeta_bin}" /bin || die 2 "Unable to copy ${luksmeta_bin}"
+copy_exec "${jose_bin}" /bin || die 2 "Unable to copy ${jose_bin}"
 
-
-copy_exec /usr/bin/clevis || die 1 "/usr/bin/clevis not found"
